apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # echo -n 'your_db_password' | base64  (Replace with your actual password BASE64 encoded)
  POSTGRES_PASSWORD: V2VsY29tZUAxMjM=
  # Optional: If your username is not 'myuser' encode it too
  POSTGRES_USER: dHRz