apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: user-registration-service
  ports:
  - protocol: TCP
    port: 8081       # Service port
    targetPort: 8081 # Container port
    nodePort: 30001 # Example static NodePort (optional, choose from 30000-32767)
  type: NodePort # Expose externally via node IP:nodePort